# Generated by Django 5.2.7 on 2025-10-29 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='funnel_stage',
            field=models.CharField(choices=[('sales_initial', 'Chat Inicial'), ('sales_negotiation', 'Negociación'), ('sales_debate', 'Debate'), ('sales_closing', 'Finalización'), ('support_initial', 'Contacto Inicial'), ('support_process', 'Proceso de Soporte'), ('support_closing', 'Finalización'), ('recovery_initial', 'Contacto Inicial'), ('recovery_evaluation', 'Evaluación'), ('recovery_proposal', 'Propuesta'), ('recovery_followup', 'Seguimiento'), ('recovery_closing', 'Cierre'), ('none', 'Sin Embudo')], default='none', max_length=30),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='funnel_type',
            field=models.CharField(choices=[('sales', 'Ventas'), ('support', 'Soporte'), ('recovery', 'Recuperación'), ('none', 'Ninguno')], default='none', max_length=20),
        ),
        migrations.CreateModel(
            name='RecoveryCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('price_objection', 'Objeción de Precio'), ('competitor', 'Se fue a la Competencia'), ('timing', 'Mal Momento'), ('feature_missing', 'Falta de Funcionalidad'), ('service_issue', 'Problema de Servicio'), ('communication', 'Falla de Comunicación'), ('other', 'Otro')], max_length=20)),
                ('reason_notes', models.TextField(blank=True, help_text='Detalles específicos sobre la razón', null=True)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('recovered', 'Recuperado'), ('lost', 'Perdido Definitivamente'), ('paused', 'Pausado')], default='active', max_length=20)),
                ('recovery_strategy', models.TextField(blank=True, help_text='Estrategia planificada para la recuperación', null=True)),
                ('attempts_count', models.IntegerField(default=0, help_text='Número de intentos de contacto')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('target_recovery_date', models.DateField(blank=True, help_text='Fecha objetivo para recuperación', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_cases_assigned', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_cases', to='core.contact')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_case', to='core.conversation')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_cases_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recovery_cases',
                'unique_together': {('contact', 'conversation')},
            },
        ),
    ]
