# Generated by Django 5.2.7 on 2025-10-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_needs_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='case_type',
            field=models.CharField(choices=[('sales', 'Ventas'), ('support', 'Soporte'), ('recovery', 'Recuperación')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('support', 'Soporte'), ('sales', 'Ventas/Recuperación')], default='support', max_length=20),
        ),
    ]
