# Generated by Django 5.2.7 on 2025-11-06 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_lead_case_type_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('meeting', 'Reunión'), ('call', 'Llamada'), ('follow_up', 'Seguimiento'), ('demo', 'Demostración'), ('support', 'Soporte Técnico'), ('other', 'Otro')], default='meeting', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Programado'), ('confirmed', 'Confirmado'), ('completed', 'Completado'), ('cancelled', 'Cancelado'), ('rescheduled', 'Reprogramado')], default='scheduled', max_length=20)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('timezone', models.CharField(default='America/Lima', max_length=50)),
                ('google_event_id', models.CharField(blank=True, help_text='ID del evento en Google Calendar', max_length=255, null=True)),
                ('google_calendar_link', models.URLField(blank=True, help_text='Enlace al evento en Google Calendar', null=True)),
                ('send_notification', models.BooleanField(default=True, help_text='Enviar notificación al cliente')),
                ('notification_sent', models.BooleanField(default=False)),
                ('reminder_minutes', models.IntegerField(default=15, help_text='Minutos antes del evento para recordatorio')),
                ('is_synced', models.BooleanField(default=False, help_text='Indica si está sincronizado con Google Calendar')),
                ('sync_error', models.TextField(blank=True, help_text='Error de sincronización si existe', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(help_text='Agente responsable del evento', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_events', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='core.conversation')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'calendar_events',
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='GoogleCalendarConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_calendar_id', models.CharField(blank=True, help_text='ID del calendario de Google', max_length=255, null=True)),
                ('access_token', models.TextField(blank=True, help_text='Token de acceso OAuth2', null=True)),
                ('refresh_token', models.TextField(blank=True, help_text='Token de actualización OAuth2', null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, help_text='Fecha de expiración del token', null=True)),
                ('is_connected', models.BooleanField(default=False, help_text='Indica si la cuenta está conectada')),
                ('last_sync', models.DateTimeField(blank=True, help_text='Última sincronización', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_calendar_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'google_calendar_configs',
            },
        ),
        migrations.CreateModel(
            name='EventAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('response_status', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptado'), ('declined', 'Rechazado'), ('tentative', 'Tentativo')], default='pending', max_length=20)),
                ('is_organizer', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.contact')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='core.calendarevent')),
            ],
            options={
                'db_table': 'event_attendees',
                'unique_together': {('event', 'contact', 'email')},
            },
        ),
    ]
