# Generated by Django 5.2.7 on 2025-11-10 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_calendarevent_googlecalendarconfig_eventattendee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventattendee',
            name='event',
        ),
        migrations.AlterUniqueTogether(
            name='eventattendee',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='eventattendee',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='googlecalendarconfig',
            name='user',
        ),
        migrations.DeleteModel(
            name='CalendarEvent',
        ),
        migrations.DeleteModel(
            name='EventAttendee',
        ),
        migrations.DeleteModel(
            name='GoogleCalendarConfig',
        ),
    ]
