# Generated by Django 5.2.7 on 2025-11-10 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_eventattendee_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='google_contact_checked',
            field=models.BooleanField(default=False, help_text='Indica si ya se buscó en Google Contacts'),
        ),
        migrations.AddField(
            model_name='contact',
            name='google_contact_found',
            field=models.BooleanField(default=False, help_text='Indica si se encontró en Google Contacts'),
        ),
        migrations.AddField(
            model_name='contact',
            name='google_contact_last_search',
            field=models.DateTimeField(blank=True, help_text='Última vez que se buscó en Google', null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='google_contact_name',
            field=models.CharField(blank=True, help_text='Nombre obtenido de Google Contacts', max_length=255, null=True),
        ),
    ]
