# Generated by Django 5.2.7 on 2025-11-10 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_contact_google_contact_checked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='google_contact_checked',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='google_contact_found',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='google_contact_last_search',
        ),
        migrations.AddField(
            model_name='contact',
            name='google_contact_id',
            field=models.CharField(blank=True, help_text='ID del contacto en Google Contacts', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='google_last_sync',
            field=models.DateTimeField(blank=True, help_text='Última vez que se sincronizó con Google Contacts', null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='google_contact_name',
            field=models.CharField(blank=True, help_text='Nombre encontrado en Google Contacts', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='GoogleContactsAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(help_text='Token de acceso de Google OAuth2')),
                ('refresh_token', models.TextField(blank=True, help_text='Token de refresh de Google OAuth2', null=True)),
                ('token_expires_at', models.DateTimeField(help_text='Fecha de expiración del token')),
                ('scopes', models.JSONField(default=list, help_text='Scopes autorizados')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_contacts_auth', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'google_contacts_auth',
            },
        ),
    ]
